# Generated by Django 2.0.1 on 2018-01-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
                ('sername', models.CharField(max_length=32, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=32, verbose_name='отчество ')),
            ],
        ),
    ]
